[package]
name = "pragmatic_logger"
version = "0.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "pragmatic_logger"
path = "src/lib.rs"


[dependencies]
chrono = "=0.4.19"

[profile.release]
lto = true
